name: Feature
description: Create a feature issue
title: "[Feature] "
labels:
  - feature
assignees: hurrry-woodvil
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: What this feature implement
      placeholder: e.g. Allow only authenticated users to use the application
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: Why is this feature needed
      placeholder: e.g. Restrict access for unauthenticated users to ensure security
    validations:
      required: true
