name: Implement
description: Issue for implementation step within a task
title: "[Implement] "
labels:
  - implement
assignees: hurry-woodvil
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: What will be implemented in this issue
      placeholder: e.g. Add request / response types for login API
    validations:
      required: true

  - type: textarea
    id: plan
    attributes:
      label: Plan
      description: Implementation steps or checklist
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true
