name: Task
description: Issue for a work unit to complete a feature
title: "[Task] "
labels:
  - task
assignees: hurry-woodvil
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: What this task will do
      placeholder: e.g. Implement login API
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: The state when this task is completed
      placeholder: e.g. Authenticate with email and password and return access / refresh tokens
    validations:
      required: true
